//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSupervisor_Beta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class allocation
    {
        public int id { get; set; }
        public Nullable<int> studentID { get; set; }
        public Nullable<int> supervisorID { get; set; }
        public Nullable<int> secondmarkerID { get; set; }
        public Nullable<int> projectID { get; set; }
    
        public virtual project project { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
    }
}
