//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSupervisor_Beta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fileUpload
    {
        public int id { get; set; }
        public string fileUri { get; set; }
        public Nullable<int> postID { get; set; }
    
        public virtual post post { get; set; }
    }
}
