//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSupervisor_Beta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interaction
    {
        public int id { get; set; }
        public Nullable<int> studentID { get; set; }
        public Nullable<int> interactionTypeID { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    
        public virtual interactionType interactionType { get; set; }
        public virtual user user { get; set; }
    }
}
